// Generated by https://quicktype.io
// For a single anime response object

import { CoverImage, NextAiringEpisode, Season } from "./IQuery";

export interface IQueryId {
  data: Data;
}

export interface Data {
  Media: Media;
}

export interface Media {
  id: number;
  title: MediaTitle;
  averageScore: number | null;
  bannerImage: string | null;
  characters: Characters;
  coverImage: CoverImage;
  description: string | null;
  duration: number | null;
  endDate: EndDateClass;
  episodes: number | null;
  externalLinks: ExternalLink[];
  favourites: number;
  format: string;
  genres: string[];
  meanScore: number | null;
  nextAiringEpisode: NextAiringEpisode | null;
  popularity: number;
  rankings: Ranking[];
  recommendations: Recommendations;
  relations: Relations;
  season: Season | null;
  seasonYear: number | null;
  source: string | null;
  staff: Staff;
  startDate: EndDateClass;
  stats: Stats;
  status: string;
  streamingEpisodes: StreamingEpisodes[];
  studios: Studios;
  synonyms: string[];
  tags: Tag[];
  trailer: Trailer | null;
}

export interface Characters {
  edges: CharactersEdge[];
}

export interface CharactersEdge {
  node: VoiceActorClass;
  role: string;
  voiceActors: VoiceActorClass[];
}

export interface VoiceActorClass {
  image: Image;
  name: Name;
}

export interface Image {
  large: string;
}

export interface Name {
  full: string;
}

export interface EndDateClass {
  year: number | null;
  month: number | null;
  day: number | null;
}

export interface ExternalLink {
  site: string;
  url: string;
}

export interface Ranking {
  rank: number;
  type: string;
  year: number | null;
  season: string | null;
  allTime: boolean;
  context: string;
}

export interface Recommendations {
  nodes: RecommendationsNode[];
}

export interface RecommendationsNode {
  mediaRecommendation: MediaRecommendation;
}

export interface MediaRecommendation {
  id: number;
  title: MediaRecommendationTitle;
  coverImage: MediaRecommendationCoverImage;
}

export interface MediaRecommendationCoverImage {
  extraLarge: string;
}

export interface MediaRecommendationTitle {
  romaji: string;
}

export interface Relations {
  edges: RelationsEdge[];
  nodes: RelationsNode[];
}

export interface RelationsEdge {
  relationType: string;
}

export interface RelationsNode {
  title: MediaRecommendationTitle;
  format: string;
  status: string;
  coverImage: MediaRecommendationCoverImage;
}

export interface Staff {
  edges: StaffEdge[];
}

export interface StaffEdge {
  role: string;
  node: VoiceActorClass;
}

export interface Stats {
  statusDistribution: StatusDistribution[];
}

export interface StatusDistribution {
  status: string;
  amount: number;
}

interface StreamingEpisodes {
  title: string;
  thumbnail: string;
  url: string;
}

export interface Studios {
  nodes: StudiosNode[];
}

export interface StudiosNode {
  name: string;
  isAnimationStudio: boolean;
}

export interface Tag {
  rank: number;
  name: string;
}

export interface MediaTitle {
  romaji: string;
  english: string | null;
  native: string | null;
}

export interface Trailer {
  id: string;
  site: string;
}
